# For more information, see https://github.com/casey/just

PYTHON_FILE := "neural_net_cli.py"
PYTHON_PATH := "./venv/bin/python"

# set up the venv
setup:
    python3 -m venv venv --prompt "neural-net"
    ./venv/bin/pip install --upgrade pip
    ./venv/bin/pip install -r requirements.txt

# run manual training
manual:
    {{PYTHON_PATH}} {{PYTHON_FILE}} manual

# run optuna optimization
optuna:
    {{PYTHON_PATH}} {{PYTHON_FILE}} optuna
