# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: leaf/leaf.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'leaf/leaf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fleaf/leaf.proto\x12\x04leaf\x1a\x13\x63ommon/common.proto\"K\n\x13ScheduleCallRequest\x12&\n\nfunctionID\x18\x01 \x01(\x0b\x32\x12.common.FunctionID\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"B\n\x14ScheduleCallResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x1c\n\x05\x65rror\x18\x02 \x01(\x0b\x32\r.common.Error\"\\\n\x15\x43reateFunctionRequest\x12#\n\timage_tag\x18\x01 \x01(\x0b\x32\x10.common.ImageTag\x12\x1e\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0e.common.Config\"@\n\x16\x43reateFunctionResponse\x12&\n\nfunctionID\x18\x01 \x01(\x0b\x32\x12.common.FunctionID2\x9a\x01\n\x04Leaf\x12\x45\n\x0cScheduleCall\x12\x19.leaf.ScheduleCallRequest\x1a\x1a.leaf.ScheduleCallResponse\x12K\n\x0e\x43reateFunction\x12\x1b.leaf.CreateFunctionRequest\x1a\x1c.leaf.CreateFunctionResponseB-Z+github.com/3s-rg-codes/HyperFaaS/proto/leafb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leaf.leaf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/3s-rg-codes/HyperFaaS/proto/leaf'
  _globals['_SCHEDULECALLREQUEST']._serialized_start=46
  _globals['_SCHEDULECALLREQUEST']._serialized_end=121
  _globals['_SCHEDULECALLRESPONSE']._serialized_start=123
  _globals['_SCHEDULECALLRESPONSE']._serialized_end=189
  _globals['_CREATEFUNCTIONREQUEST']._serialized_start=191
  _globals['_CREATEFUNCTIONREQUEST']._serialized_end=283
  _globals['_CREATEFUNCTIONRESPONSE']._serialized_start=285
  _globals['_CREATEFUNCTIONRESPONSE']._serialized_end=349
  _globals['_LEAF']._serialized_start=352
  _globals['_LEAF']._serialized_end=506
# @@protoc_insertion_point(module_scope)
