default:
	@just --list

build:
	node build.js

run:
	k6 run generated/k6-script.js

clean: 
	rm -rf generated

run-with-output:
	k6 run  --out csv=test_results.csv script.js

export-metrics:
	uv run ../benchmarks/import_metrics.py --csv test_results.csv --db ../benchmarks/metrics.db