default:
	@just --list

build:
	node build.js

run:
	k6 run generated/k6-script.js

clean: 
	rm -rf generated

run-with-output:
	k6 run  --out csv=test_results.csv script.js

export-metrics:
	uv run ../benchmarks/import_metrics.py --csv test_results.csv --db ../benchmarks/metrics.db


run-seeded:
	k6 run \
	--quiet \
	--out csv=test_results.csv \
	-e WORKLOAD_SEED=12345 \
	-e PERSIST_GENERATION=true \
	-e TOTAL_TEST_DURATION="10m" \
	-e MIN_PREALLOCATED_VUS=10 \
	-e MAX_PREALLOCATED_VUS=50 \
	-e MIN_MAX_VUS=100 \
	-e MAX_MAX_VUS=800 \
	-e RAMPING_START_RATE_MIN=1 \
	-e RAMPING_START_RATE_MAX=5 \
	-e BFS_MIN_SCENARIOS=5 \
	-e BFS_MAX_SCENARIOS=8 \
	-e BFS_CONSTANT_SCENARIOS_RATIO=0.6 \
	-e BFS_CONSTANT_RATE_MIN=100 \
	-e BFS_CONSTANT_RATE_MAX=300 \
	-e BFS_BURST_TARGET_RATE_MIN=300 \
	-e BFS_BURST_TARGET_RATE_MAX=600 \
	-e ECHO_MIN_SCENARIOS=5 \
	-e ECHO_MAX_SCENARIOS=8 \
	-e ECHO_CONSTANT_SCENARIOS_RATIO=0.5 \
	-e ECHO_CONSTANT_RATE_MIN=100 \
	-e ECHO_CONSTANT_RATE_MAX=300 \
	-e ECHO_BURST_TARGET_RATE_MIN=300 \
	-e ECHO_BURST_TARGET_RATE_MAX=800 \
	-e THUMBNAILER_MIN_SCENARIOS=2 \
	-e THUMBNAILER_MAX_SCENARIOS=8 \
	-e THUMBNAILER_CONSTANT_SCENARIOS_RATIO=0.8 \
	-e THUMBNAILER_CONSTANT_RATE_MIN=40 \
	-e THUMBNAILER_CONSTANT_RATE_MAX=80 \
	-e THUMBNAILER_BURST_TARGET_RATE_MIN=100 \
	-e THUMBNAILER_BURST_TARGET_RATE_MAX=200 \
	script.js > generated_scenarios.json